### PR TITLE
Implement Adapter.SupportsExtendedAdvertising on Windows

### PR DESCRIPTION
**Pull request by janusw**
see the discussion in #815

### CODE REVIEW

**Comment by axa88** [comment]
> @axa88 Could you check if this works well for you? (Testing on Windows is not fully impossible but rather effortful for me). There is a nupkg built by GHA which you can use for testing.

Im not entirely sure of what i need to confirm proper functionality.
But i do know i do not have Windows hardware that supports extended advertising...

**Comment by janusw** [comment]
> > @axa88 Could you check if this works well for you? (Testing on Windows is not fully impossible but rather effortful for me). There is a nupkg built by GHA which you can use for testing.
> 
> Im not entirely sure of what i need to confirm proper functionality. But i do know i do not have Windows hardware that supports extended advertising...

Well, in that case it would be enough if you could simply confirm that `SupportsExtendedAdvertising` still returns `false`, as before (and there are no exceptions or errors).

I'll check if I have some Windows hardware that supports extended advertising.

**Comment by axa88** [comment]
> Well, in that case it would be enough if you could simply confirm that `SupportsExtendedAdvertising` still returns `false`, as before (and there are no exceptions or errors).

Things continue to work as they did..

**Comment by janusw** [comment]
> > Well, in that case it would be enough if you could simply confirm that `SupportsExtendedAdvertising` still returns `false`, as before (and there are no exceptions or errors).
> 
> Things continue to work as they did..

Thanks for the confirmation. I also managed to test this by now, but my Windows test device also returns `false` (an oldish Dell XPS 13 notebook). In any case this is enough to verify that the native API call works correctly, so I will merge this simple PR.

**Pull request merged**
