### PR TITLE
UWP Support Rebased from Branch uwp_creators_update

### PR DESCRIPTION
**Pull request by JanNepras**
This pr is rebased from uwp_creators_update branch. It contains support for uwp platform. 

The build agent was changed to "windows-latest" in dotnet.yaml.

### CODE REVIEW

**Comment by JanNepras** [comment]
@janusw Could you please review this pr? Could we get this into nuget feed as a preview version? To release these changes a preview version do we have to do it manually or is there any pipeline setup?

**Comment by JanNepras** [comment]
@janusw I found out that this version won't work. Could you give me the access to nuget feed? I add only the preview version once I fix this.

**Comment by janusw** [comment]
> @janusw I found out that this version won't work.

Could you please share with us what exactly does not work?

In general, if we want to make progress with UWP, it would be useful to collect all things that are still missing or that do not work. E.g. there are the following open issues tagged as `os:UWP`:
https://github.com/xabre/xamarin-bluetooth-le/issues?q=is%3Aissue+is%3Aopen+label%3Aos%3AUWP

> Could you give me the access to nuget feed? I add only the preview version once I fix this.

Let me slow you down a little here ...

 First your 'issue' should be fixed (whatever it is, please describe). Second, your modifications should be checked and reviewed by somebody else before we release anything. (Note that I personally might not be to best person to review it. I don't work on Windows at all. But I hope there might be others who are interested in UWP ...)

Furthermore, as mentioned before, I plan to prepare a release 2.1.2 (without any UWP-related changes). I'll probably do this on the weekend. Any 2.2ish UWP pre-releases should come afterwards (in order to include all the fixes from 2.1.2).

That said, the tag you set was certainly a bit premature.

So, again, let's slow down here a bit with any tags and releases, please. Sure, progress with UWP is needed, but let's not rush it too much :)

**Comment by JanNepras** [comment]
@janusw Sorry for the late response. Lately I was getting familiar with the project. You are right I should slow down.

> Could you please share with us what exactly does not work?

I thought the part of the UWP project is not build correctly and some of the classes are not visible. I found out an issue in my sample project in csproj file. 

> In general, if we want to make progress with UWP, it would be useful to collect all things...

Yes. These things should be resolved before we release it. According to me the most critical one is #423. 

Is it ok to start implementing these fixes on this branch? Or is there any different branching strategy?

**Comment by JanNepras** [comment]
@janusw I was trying to resolve #423 with no luck. I tried to dispose services and their characteristics which is [described here](https://stackoverflow.com/questions/47702584/bluetooth-le-device-cannot-disconnect-in-win-10-iot-uwp-application). Do you have any idea how to resolve this issue?

**Comment by janusw** [comment]
I'm closing this for now. It is outdated and was not very clean to begin with. There will be a new effort to sync the existing UWP stuff with master, see the recent discussion in #591.

**Pull request closed without merging**
