### PR TITLE
Fixed StartUpdatesNativeAsync for indicate

### LINKED ISSUE #847: Need to be able to register for notification from characteristics that is only INDICATE
To help us fix your issue, please provide the information in the below template. If something causes a crash, provide as much information as you can gather.
Just imagine: we do not know what you are doing! 

> Note: There is often little we can do without a minimal reproducible sample of the issue, so please provide that in a **standalone git repository** and link it here.

## Steps to reproduce

1. Try to use a peripheral with a characteristic with only INDICATE

2.

3.

## Expected behavior
Registration for updates should succeed

## Actual behavior
Registration is not performed. The Windows implementation of the StartUpdatesNativeAsync only register in case of Notify.
It could be solved this way
            GattWriteResult result;
            if (NativeCharacteristic.CharacteristicProperties.HasFlag(GattCharacteristicProperties.Indicate))
                result = await NativeCharacteristic.WriteClientCharacteristicConfigurationDescriptorWithResultAsync(GattClientCharacteristicConfigurationDescriptorValue.Indicate);
            else
                result = await NativeCharacteristic.WriteClientCharacteristicConfigurationDescriptorWithResultAsync(GattClientCharacteristicConfigurationDescriptorValue.Notify);

### Crashlog

If something causes an exception paste full stack trace + Exception here

## Configuration

**Version of the Plugin:** e.g. 1.0.0 / 1.0.1-alpha3
3.1.0-rc.1

**Platform:** e.g. iOS 10.1 / Android 4.4 / ... (including version!!! e.g. Android 5.1 / i0S 10)
UWP/Windows 10

**Device:** e.g. HTC Sensation /i Phone 7 ...

### PR DESCRIPTION
**Pull request by AskBojesen**
To fix #847

### CODE REVIEW

**Comment by CodeMusher** [comment]
@janusw, I haven't got the possibility to verify it today but it looks almost identical to the solution I provided when opening the issue so I guess it must.

**Comment by janusw** [comment]
> @janusw, I haven't got the possibility to verify it today

No problem. When will you be able to verify it?

> but it looks almost identical to the solution I provided when opening the issue

Yes, it's very close, but not identical.

> so I guess it must.

Sorry, but guessing is not good enough here. Apparently @AskBojesen was not able to reproduce the issue and test the fix, and I'm not going to accept an untested PR at this stage (i.e. directly before a stable release).

**Comment by CodeMusher** [comment]
I'll try to test it tomorrow

**Comment by AskBojesen** [comment]
BTW: I have tested using my "normal" device with Notity in char descriptors  - and that still works as expected.

**Comment by CodeMusher** [comment]
Now I have tested with two different devices. One with characteristics with only INDICATE and one with a mixed population of characteristics, some INDICATE and some NOTIFY. 
It works as expected!

**Review by janusw — APPROVED** [review]
Since both of you have tested it and code-wise it looks very clean, this is ok with me. Thanks for fixing this so quickly, @AskBojesen!

**Pull request merged**
