### PR TITLE
Windows: Fixed null entries in DiscoveredDevices  #828

### PR DESCRIPTION
**Pull request by AskBojesen**
To fix https://github.com/dotnet-bluetooth-le/dotnet-bluetooth-le/issues/828

### CODE REVIEW

**Comment by axa88** [comment]
@janusw 
Surely this isn't a question exclusive for this repo, but its the repo i find myself messing around with lots of bleeding edge versions... 
So how can i ensure i get a new installation of a package if the build version doesnt change, without wiping away my package cache?
I caught myself _again_ thinking my package had updated where it didnt... and im pretty sure its due to using the same version as i had installed previously

Or is there a way to build these things with semantic versioning...  Perhaps rolling that last digit with each build?

**Comment by axa88** [comment]
> hat this fixes t

seems to fixed `WinUI`.  But would you believe it Scanning on `Android`, badly. good thing i tried it first.

I cant even keep the debugger open long enough to investigate...
Did something with advertisements change?

```
18:45:23:471	[BluetoothLeScanner] Start Scan with callback
18:45:23:471	[BluetoothLeScanner] onScannerRegistered() - status=0 scannerId=12 mScannerId=0
18:45:23:532	[BluetoothAdapter] BluetoothAdapter() : com.companyname.testsmaui
18:45:24:578	herehherehere
18:45:26:734	**System.ArgumentException:** 'An item with the same key has already been added. Key: ManufacturerSpecificData'
18:45:26:734	
18:45:34:696	Thread started: <Thread Pool> #6
18:45:34:696	The vm is not suspended.
18:45:34:696	Mono.Debugger.Soft.VMNotSuspendedException: The vm is not suspended.
18:45:34:696	   at Mono.Debugger.Soft.VirtualMachine.ErrorHandler(Object sender, ErrorHandlerEventArgs args) in D:\a\_work\1\s\External\debugger-libs\Mono.Debugger.Soft\Mono.Debugger.Soft\VirtualMachine.cs:line 369
18:45:34:696	   at Mono.Debugger.Soft.Connection.SendReceive(CommandSet command_set, Int32 command, PacketWriter packet) in D:\a\_work\1\s\External\debugger-libs\Mono.Debugger.Soft\Mono.Debugger.Soft\Connection.cs:line 1894
18:45:34:696	   at Mono.Debugger.Soft.VirtualMachine.Resume() in D:\a\_work\1\s\External\debugger-libs\Mono.Debugger.Soft\Mono.Debugger.Soft\VirtualMachine.cs:line 139
18:45:34:696	   at Mono.Debugging.Soft.SoftDebuggerSession.HandleEventSet(EventSet es) in D:\a\_work\1\s\External\debugger-libs\Mono.Debugging.Soft\SoftDebuggerSession.cs:line 1903
18:45:34:696	   at Mono.Debugging.Soft.SoftDebuggerSession.EventHandler() in D:\a\_work\1\s\External\debugger-libs\Mono.Debugging.Soft\SoftDebuggerSession.cs:line 1801

```
Do not commit.

**Comment by janusw** [comment]
> @janusw Surely this isn't a question exclusive for this repo, but its the repo i find myself messing around with lots of bleeding edge versions... So how can i ensure i get a new installation of a package if the build version doesnt change, without wiping away my package cache? I caught myself _again_ thinking my package had updated where it didnt... and im pretty sure its due to using the same version as i had installed previously
> 
> Or is there a way to build these things with semantic versioning... Perhaps rolling that last digit with each build?
> 
> I now see there is a build number added to the interface, probably a VS problem... I just have to figure out how to properly clean and rebuild i guess

Actually for testing PRs, there is no need to build things yourself (you can, but I don't recommend it). Instead, you can use the nuget packages that are built from the GitHub Actions CI. Just go to "Checks" in the tab bar of the PR, and then select artifacts and download the nupkg (which is uniquely versioned via `git describe`). For this PR, the direct link to the package is https://github.com/dotnet-bluetooth-le/dotnet-bluetooth-le/actions/runs/9001637781/artifacts/1484044786

**Comment by axa88** [comment]
> > @janusw Surely this isn't a question exclusive for this repo, but its the repo i find myself messing around with lots of bleeding edge versions... So how can i ensure i get a new installation of a package if the build version doesnt change, without wiping away my package cache? I caught myself _again_ thinking my package had updated where it didnt... and im pretty sure its due to using the same version as i had installed previously
> > Or is there a way to build these things with semantic versioning... Perhaps rolling that last digit with each build?
> > I now see there is a build number added to the interface, probably a VS problem... I just have to figure out how to properly clean and rebuild i guess
> 
> Actually for testing PRs, there is no need to build things yourself (you can, but I don't recommend it). Instead, you can use the nuget packages that are built from the GitHub Actions CI. Just go to "Checks" in the tab bar of the PR, and then select artifacts and download the nupkg (which is uniquely versioned via `git describe`). For this PR, the direct link to the package is https://github.com/dotnet-bluetooth-le/dotnet-bluetooth-le/actions/runs/9001637781/artifacts/1484044786

ya i figured it out thanks

**Comment by axa88** [comment]
> > seems to fixed `WinUI`. But would you believe it Scanning on `Android`, badly. good thing i tried it first.
> > Do not commit. cc @janusw
> 
> This PR touches Windows only. If there is a problem with Android, it's already there on master / 3.0.0-rc.1.

> 
> Do you have a proper backtrace for the exception you see? If it is really a problem with the library (and not with the way you use it), then please open a new issue for it.

@janusw 
do you mean 3.1 rc1?
Either way ya perhaps it traces back to something or the way im using it. Ill investigate

**Comment by janusw** [comment]
> @janusw do you mean 3.1 rc1?

Yes, sorry, I meant 3.1.0-rc.1 of course.

> Either way ya perhaps it traces back to something or the way im using it. Ill investigate

In fact I have tested receiving advertisements with 3.1.0-rc.1 on Android (plus the latest changes in that release were basically all Windows-related), so I'd be rather surprised if something is seriously broken on Android (but it's not completely impossible, of course 😜).

**Comment by AskBojesen** [comment]
But, @janusw: Can we then get this approved to keep this PR on track?

**Comment by axa88** [comment]
ok this addresses the given issue.
@janusw 
Any other problems Im having is due to my broken implementation

**Review by janusw — APPROVED** [review]
Alright, if it fixes the problem, this is certainly ok with me. It seems the relevant parts of the problematic commit are simply reverted.

Thanks for the fix, @AskBojesen, and thanks for the bug report and testing, @axa88 !

**Pull request merged**
