### PR TITLE
StateChanged for Windows

### PR DESCRIPTION
**Pull request by AskBojesen**
Implemented StateChanged for Windows

### CODE REVIEW

**Comment by AskBojesen** [comment]
Hi again @janusw - Yet another little PR.
I have a few more PR's in the pipeline for the Windows implementation...
What do you prefer - small PR's or one big cumulative PR?

**Comment by janusw** [comment]
> Hi again @janusw - Yet another little PR.

👍 

> I have a few more PR's in the pipeline for the Windows implementation... What do you prefer - small PR's or one big cumulative PR?

I prefer small PRs (if they are functionally well separated). Or at least reasonably small commits.

Small PRs make reviewing easier. Small commits make it easier to determine (in hindsight) when and where a particular problem was introduced.

**Comment by AskBojesen** [comment]
> > Hi again @janusw - Yet another little PR.
> 
> 👍
> 
> > I have a few more PR's in the pipeline for the Windows implementation... What do you prefer - small PR's or one big cumulative PR?
> 
> I prefer small PRs (if they are functionally well separated). Or at least reasonably small commits.
> 
> Small PRs make reviewing easier. Small commits make it easier to determine (in hindsight) when and where a particular problem was introduced.

Great - then you can just approve this ;-)

**Review by janusw — APPROVED** [review]
> Great - then you can just approve this ;-)

Yes I can 💪. LGTM. Thanks for the contribution.

**Pull request merged**
