### PR TITLE
Fix GetSystemConnectedOrPairedDevices in Windows

### PR DESCRIPTION
**Pull request by AskBojesen**
Also Improved WinConsole Demo Client - Solves half of #800 

@janusw : Trust you to set the labels on this PR. 

It is the smallest PR so far - only one line changed in the Adapter.cs: `BluetoothDevice` -> BluetoothLEDevice

### CODE REVIEW

**Comment by AskBojesen** [comment]
@Auto72: Will you test?

**Comment by Auto72** [comment]
You can use the following code to test the .GetSystemConnectedOrPairedDevices() method in your WinConsole example:

    using Plugin.BLE;

    var systemDevices = CrossBluetoothLE.Current.Adapter.GetSystemConnectedOrPairedDevices();
    if (systemDevices is not null)
    {
        Console.WriteLine($"GetSystemConnectedOrPairedDevices() | Number of paired devices: {systemDevices.Count}");
        foreach (var device in systemDevices)
        {
            Console.WriteLine($"{device.Name}");
        }
    }
    else { Console.WriteLine($"GetSystemConnectedOrPairedDevices() no paired devices found."); }

Where can I download your modified version? Can you put me the link, please?

**Comment by AskBojesen** [comment]
> You can use the following code to test the .GetSystemConnectedOrPairedDevices() method in your WinConsole example:
> 
> ```
> using Plugin.BLE;
> 
> var systemDevices = CrossBluetoothLE.Current.Adapter.GetSystemConnectedOrPairedDevices();
> if (systemDevices is not null)
> {
>     Console.WriteLine($"GetSystemConnectedOrPairedDevices() | Number of paired devices: {systemDevices.Count}");
>     foreach (var device in systemDevices)
>     {
>         Console.WriteLine($"{device.Name}");
>     }
> }
> else { Console.WriteLine($"GetSystemConnectedOrPairedDevices() no paired devices found."); }
> ```
> 
> Where can I download your modified version? Can you put me the link, please, so I can test it. Thanks.

Use this repository: 
https://github.com/AskBojesen/dotnet-bluetooth-le/tree/fix_get_system_connected_or_paired_devices_in_windows

Open the BLE.sln and set Samples/WInConsole as startup project 

Then run

**Comment by Auto72** [comment]
@AskBojesen 

The GetSystemConnectedOrPairedDevices() still doesn't work on Windows.



You need to use:

string selector = **BluetoothLEDevice**.GetDeviceSelectorFromPairingState(true);

Instead of:

string pairedSelector = BluetoothDevice.GetDeviceSelectorFromPairingState(true);

Please, you can include the test code for GetSystemConnectedOrPairedDevices() I posted above in your BLE.Client.WinConsole project, inside the file program.cs.

Thanks.

**Comment by AskBojesen** [comment]
> @AskBojesen
> 
> The GetSystemConnectedOrPairedDevices() still doesn't work on Windows.
> 
> 
> 
> You need to use:
> 
> string selector = **BluetoothLEDevice**.GetDeviceSelectorFromPairingState(true);
> 
> Instead of:
> 
> string pairedSelector = BluetoothDevice.GetDeviceSelectorFromPairingState(true);
> 
> Please, you can include the test code for GetSystemConnectedOrPairedDevices() I posted above in your BLE.Client.WinConsole project, inside the file program.cs.
> 
> Thanks.

But the branch for this PR has the correct implementation

https://github.com/AskBojesen/dotnet-bluetooth-le/blob/fix_get_system_connected_or_paired_devices_in_windows/Source/Plugin.BLE/Windows/Adapter.cs

**Comment by Auto72** [comment]
I don't know. If I get the from here: 

https://github.com/AskBojesen/dotnet-bluetooth-le/tree/fix_get_system_connected_or_paired_devices_in_windows

And debug the BLE.Client.WinConsole project, adding the following source code:

```
    var blePresent = CrossBluetoothLE.Current.IsAvailable;
    var bleEnabled = CrossBluetoothLE.Current.IsOn;

    Console.WriteLine($"\nCrossBluetoothLE.Current.IsAvailable: {blePresent} | CrossBluetoothLE.Current.IsOn: {bleEnabled}\n");

    var systemDevices = CrossBluetoothLE.Current.Adapter.GetSystemConnectedOrPairedDevices();
    if (systemDevices is not null)
    {
        Console.WriteLine($"GetSystemConnectedOrPairedDevices() | Number of paired devices: {systemDevices.Count}");
        foreach (var device in systemDevices)
        {
            Console.WriteLine($"{device.Name}");
        }
        Console.WriteLine("\n");
    }
    else { Console.WriteLine($"GetSystemConnectedOrPairedDevices() no paired devices found.\n"); }
```
I find what I reported on the screenshot above.

**Comment by AskBojesen** [comment]
> I don't know. If I get code from here:
> 
> https://github.com/AskBojesen/dotnet-bluetooth-le/tree/fix_get_system_connected_or_paired_devices_in_windows
> 
> And debug the BLE.Client.WinConsole project, adding the following source code:
> 
> ```
>     var blePresent = CrossBluetoothLE.Current.IsAvailable;
>     var bleEnabled = CrossBluetoothLE.Current.IsOn;
> 
>     Console.WriteLine($"\nCrossBluetoothLE.Current.IsAvailable: {blePresent} | CrossBluetoothLE.Current.IsOn: {bleEnabled}\n");
> 
>     var systemDevices = CrossBluetoothLE.Current.Adapter.GetSystemConnectedOrPairedDevices();
>     if (systemDevices is not null)
>     {
>         Console.WriteLine($"GetSystemConnectedOrPairedDevices() | Number of paired devices: {systemDevices.Count}");
>         foreach (var device in systemDevices)
>         {
>             Console.WriteLine($"{device.Name}");
>         }
>         Console.WriteLine("\n");
>     }
>     else { Console.WriteLine($"GetSystemConnectedOrPairedDevices() no paired devices found.\n"); }
> ```
> 
> I find what I reported on the screenshot above.

It makes no sense !?

https://github.com/AskBojesen/dotnet-bluetooth-le/blob/fix_get_system_connected_or_paired_devices_in_windows/Source/Plugin.BLE/Windows/Adapter.cs has the correct implementation. And I have tested and it works.

**Review by janusw — APPROVED** [review]
This is certainly ok with me (if you guys can agree whether it works or not 😉 ).

@Auto72 It sounds a bit like you're building from the wrong branch or so ...?!?

Note that the CI (Github Actions) also builds nupkgs, in case you want to try that way ...

**Comment by janusw** [comment]
> Note that the CI (Github Actions) also builds nupkgs, in case you want to try that way ...

see here: https://github.com/dotnet-bluetooth-le/dotnet-bluetooth-le/actions/runs/7805961543#artifacts

you can download it, set up a local package source, and use it from there. (The version is: `3.1.0-beta.1-49-ged6603e`)

**Comment by Auto72** [comment]
> > Note that the CI (Github Actions) also builds nupkgs, in case you want to try that way ...
> 
> see here: https://github.com/dotnet-bluetooth-le/dotnet-bluetooth-le/actions/runs/7805961543#artifacts
> 
> you can download it, set up a local package source, and use it from there. (The version is: `3.1.0-beta.1-49-ged6603e`)

I tried and now the GetSystemConnectedOrPairedDevices works on Windows.

**Comment by janusw** [comment]
> I tried and now the GetSystemConnectedOrPairedDevices works on Windows.

Awesome 🎉 , thanks for testing!

And of course thanks for the fix to @AskBojesen !

**Pull request merged**
