### PR TITLE
Fix a NullReferenceException in Characteristic.NSErrorToGattStatus

### PR DESCRIPTION
**Pull request by janusw**
This is supposed to fix a small bug on iOS, see #825.

### CODE REVIEW

**Comment by janusw** [comment]
@acaliaro Can you confirm that the crashes are fixed by this?

**Comment by janusw** [comment]
> @acaliaro Can you confirm that the crashes are fixed by this?

Note: You can use the nupkg built by GHA to check this ...

https://github.com/dotnet-bluetooth-le/dotnet-bluetooth-le/actions/runs/8315448842?pr=827#artifacts

**Comment by acaliaro** [comment]
> > @acaliaro Can you confirm that the crashes are fixed by this?
> 
> Note: You can use the nupkg built by GHA to check this ...
> 
> https://github.com/dotnet-bluetooth-le/dotnet-bluetooth-le/actions/runs/8315448842?pr=827#artifacts

Hi @janusw It seems like your solution solves the problem. I did various tests and the exception never showed up again.

**Comment by janusw** [comment]
> Hi @janusw It seems like your solution solves the problem. I did various tests and the exception never showed up again.

Awesome, thanks for checking 👍

**Pull request merged**
