### PR TITLE
Windows: Connect -> ConnectionLost -> Reconnect

### PR DESCRIPTION
**Pull request by AskBojesen**
To fix: https://github.com/dotnet-bluetooth-le/dotnet-bluetooth-le/issues/826

[demolog.txt](https://github.com/dotnet-bluetooth-le/dotnet-bluetooth-le/files/15251792/demolog.txt)

### CODE REVIEW

**Comment by janusw** [comment]
> To fix: #826

@CodeMusher Does this fix the problem for you?

**Comment by CodeMusher** [comment]
@janusw I’ll try to check that tomorrow!

**Comment by CodeMusher** [comment]
@janusw @AskBojesen 
Now I've tried to test the solution and it works much better now. 

For some reason the line below in the Adapter.cs for Windows throws System.InvalidCastException 
var conpar = nativeDevice.GetConnectionParameters();
It gives me the following StackTrace
 at WinRT.IObjectReference.As[T](Guid iid)
   at Windows.Devices.Bluetooth.BluetoothLEDevice.Make___objRef_global__Windows_Devices_Bluetooth_IBluetoothLEDevice6()
   at Windows.Devices.Bluetooth.BluetoothLEDevice.get__objRef_global__Windows_Devices_Bluetooth_IBluetoothLEDevice6()
   at Windows.Devices.Bluetooth.BluetoothLEDevice.GetConnectionParameters()
   at Plugin.BLE.Windows.Adapter.Device_ConnectionStatusChanged(BluetoothLEDevice nativeDevice, Object args) in C:\git\GitHub\dotnet-bluetooth-le\Source\Plugin.BLE\Windows\Adapter.cs:line 139
   at WinRT._EventSource_global__Windows_Foundation_TypedEventHandler_global__Windows_Devices_Bluetooth_BluetoothLEDevice__object_.EventState.<GetEventInvoke>b__1_0(BluetoothLEDevice sender, Object args)
   at ABI.Windows.Foundation.TypedEventHandler`2.Do_Abi_Invoke[TSenderAbi,TResultAbi](Void* thisPtr, TSenderAbi sender, TResultAbi args)
I needed to catch that exception to be able to continue. Strange, I don't think that thing isn't changed recently

**Comment by axa88** [comment]
I dont use the console demo or any other abstraction over the base library so perhaps my feedback isnt useful here, but...

Ive tested this pull and the problem i see with it is _after_ the first Connect/Disconnect cycle, a subscription to either the Adapter.DeviceConnected and Adapater.DeviceDisconnected events will be lost. 
Meaning while subsequent calls to Connect will connect, and subsequent calls to Disconnect will disconnect a device, subscription to their associated events are no longer called.

**Comment by CodeMusher** [comment]
@axa88 I’ve not tested in the real application either, but if it is like you are describing it regarding the events then it’s not good.

**Comment by CodeMusher** [comment]
Now I've tried the PR a step up in the abstraction chain, that is my test application. It seems like I get both Adapter.DeviceConnected and Adapter.DeviceConnectionLost when I power cycle my peripheral. In my setup it seems to work!

**Comment by axa88** [comment]
@CodeMusher 
> Now I've tried the PR a step up in the abstraction chain, that is my test application. It seems like I get both Adapter.DeviceConnected and Adapter.DeviceConnectionLost when I power cycle my peripheral. In my setup it seems to work!

Are you able to get `Adapter.DeviceConnected` _after_ a subsequent `Adapter.DeviceDisconnected`?

**Comment by AskBojesen** [comment]
> @janusw @AskBojesen Now I've tried to test the solution and it works much better now.
> 
> For some reason the line below in the Adapter.cs for Windows throws System.InvalidCastException var conpar = nativeDevice.GetConnectionParameters(); It gives me the following StackTrace at WinRT.IObjectReference.As[T](Guid iid) at Windows.Devices.Bluetooth.BluetoothLEDevice.Make___objRef_global__Windows_Devices_Bluetooth_IBluetoothLEDevice6() at Windows.Devices.Bluetooth.BluetoothLEDevice.get__objRef_global__Windows_Devices_Bluetooth_IBluetoothLEDevice6() at Windows.Devices.Bluetooth.BluetoothLEDevice.GetConnectionParameters() at Plugin.BLE.Windows.Adapter.Device_ConnectionStatusChanged(BluetoothLEDevice nativeDevice, Object args) in C:\git\GitHub\dotnet-bluetooth-le\Source\Plugin.BLE\Windows\Adapter.cs:line 139 at WinRT._EventSource_global__Windows_Foundation_TypedEventHandler_global__Windows_Devices_Bluetooth_BluetoothLEDevice__object_.EventState.b__1_0(BluetoothLEDevice sender, Object args) at ABI.Windows.Foundation.TypedEventHandler`2.Do_Abi_Invoke[TSenderAbi,TResultAbi](Void* thisPtr, TSenderAbi sender, TResultAbi args) I needed to catch that exception to be able to continue. Strange, I don't think that thing isn't changed recently

The  code has been in there for a while - but it is new to 3.1 vs 3.0.

It is not good if exception is thrown for the GetConnectionParameters(), because then the HandleConnectedDevice(connectedDevice) is not called.

image

Is this consequently you get this exception?

We could make a try'n'catch in the code when calling GetConnectionParameters

**Comment by janusw** [comment]
> For some reason the line below in the Adapter.cs for Windows throws System.InvalidCastException
> var conpar = nativeDevice.GetConnectionParameters();

Huh, that line as such looks rather innocent, and I don't really see why it would generate an InvalidCastException.

However `BluetoothLEDevice.GetConnectionParameters` is only available in Windows 11 (build 10.0.22000.0), and is guarded by a corresponding compile-time check. But I suspect we're missing a proper runtime API version check.

@CodeMusher Two questions:
1) Which Windows version are you targeting in your application?
2) Which Windows version are you actually running it on?

**Comment by CodeMusher** [comment]
@janusw You're right that it must be the runtime that messes it up

1. Which Windows version are you targeting in your application?
I target net8.0-windows10.0.22621.0 as that is what the WinConsole sample is using

2. Which Windows version are you actually running it on?
My laptop only runs 10.0.19045 so that must be what causing the problem.

**Comment by CodeMusher** [comment]
The tests I performed yesterday were power cycling the peripheral. These tests gave me
Adapter.DeviceConnected
Adapter.DeviceConnectionLost. 

Today I tried to initiate disconnect from the app instead. I thought that would invoke a Adapter.DeviceDisconnected. 
But it always invokes Adapter.DeviceConnectionLost.
Is that really what I should expect?

**Comment by AskBojesen** [comment]
> @janusw You're right that it must be the runtime that messes it up
> 
> 1. Which Windows version are you targeting in your application?
>    I target net8.0-windows10.0.22621.0 as that is what the WinConsole sample is using
> 2. Which Windows version are you actually running it on?
>    My laptop only runs 10.0.19045 so that must be what causing the problem.

you need runtime check if running on Windows 10, or you must use another target than 10.0.22621
Unfortunately Windows has no check for runtime - you simply get exceptions has you saw!

I have made a runtime check as custom action for the installer for our desktop app to avoid running on eg. 10.0.19045

public static int CurrentBuild()
{
    var reg = Registry.LocalMachine.OpenSubKey(@"SOFTWARE\Microsoft\Windows NT\CurrentVersion");
    var currentBuildStr = (string)reg.GetValue("CurrentBuild");
    var currentBuild = int.Parse(currentBuildStr);
    return currentBuild;
}

public override void Install(IDictionary stateSaver)
{
    // Environment.OSVersion.Version.Build does not work on .Net framework
    //int currentBuild = Environment.OSVersion.Version.Build;
    int currentBuild = CurrentBuild();
    LogText($"CurrentBuild = {currentBuild}");
    if (currentBuild < 22000)
    {
        StringBuilder sb = new StringBuilder();
        sb.AppendLine("ILab can only run on Windows 11 and higher")
                  .AppendLine()
                  .AppendLine($"CurrentBuild is {currentBuild}, which must be higher or equal to 22000");
        throw new NotSupportedException(sb.ToString());
    }
    base.Install(stateSaver);
}

**Comment by AskBojesen** [comment]
I get Adapter.DeviceDisconnected when testing with the winconsole client...

See the first lines in the attached demolog.txt

Running: Connect -> Disconnect
```
18.10.05.834 Plugin.BLE - ConnectToDeviceNativeAsync 8C4B14C9C43A Named: Egoo RD123456 Connected: Disconnected
18.10.05.835 Plugin.BLE - RequestPreferredConnectionParameters(ThroughputOptimized): Success
18.10.06.090 Plugin.BLE - Device_ConnectionStatusChanged 8C4B14C9C43A Egoo RD123456 Connected
18.10.06.090 Plugin.BLE - Connected with Latency = 0, Interval = 12, Timeout = 200
18.10.06.090       DEMO - Adapter_DeviceConnected 8C4B14C9C43A with name:  Egoo RD123456
18.10.06.090 Plugin.BLE - ConnectToDeviceAsync Connected: 00000000-0000-0000-0000-8c4b14c9c43a Egoo RD123456
18.10.06.090       DEMO - Waiting 5 secs
18.10.06.090 Plugin.BLE - GattSession_SessionStatusChanged: Active
18.10.06.253 Plugin.BLE - GattSession_MaxPduSizeChanged: 517
18.10.11.085       DEMO - Disconnecting
18.10.11.085 Plugin.BLE - DisconnectDeviceNative from device with ID:  8C4B14C9C43A
18.10.14.191 Plugin.BLE - Device_ConnectionStatusChanged 8C4B14C9C43A Egoo RD123456 Disconnected
**18.10.14.191 Plugin.BLE - DisconnectedPeripheral by user: Egoo RD123456
18.10.14.191       DEMO - Adapter_DeviceDisconnected 8C4B14C9C43A with name: Egoo RD123456**
18.10.14.191 Plugin.BLE - DisconnectAsync Disconnected: 00000000-0000-0000-0000-8c4b14c9c43a Egoo RD123456
18.10.14.191       DEMO - Test_Connect_Disconnect done
```

**Comment by CodeMusher** [comment]
@AskBojesen > you need runtime check if running on Windows 10, or you must use another target than 10.0.22621 Unfortunately Windows has no check for runtime - you simply get exceptions has you saw!
> 
> I have made a runtime check as custom action for the installer for our desktop app to avoid running on eg. 10.0.19045
> 

Ok, I'll keep that in mind, missed that one.

**Comment by janusw** [comment]
> > @janusw You're right that it must be the runtime that messes it up
> > 
> > 1. Which Windows version are you targeting in your application?
> >    I target net8.0-windows10.0.22621.0 as that is what the WinConsole sample is using
> > 2. Which Windows version are you actually running it on?
> >    My laptop only runs 10.0.19045 so that must be what causing the problem.

Thanks for the info. This indeed confirms my suspicion.

> you need runtime check if running on Windows 10, or you must use another target than 10.0.22621 Unfortunately Windows has no check for runtime - you simply get exceptions has you saw!

Well, I think the library should better guard the version-dependent code by a runtime check and only execute it if it's supported (see https://learn.microsoft.com/en-us/windows/uwp/debug-test-perf/version-adaptive-apps).

For `BluetoothLEDevice.GetConnection` one needs to check for `UniversalApiContract` v14 AFAICS.

**Comment by CodeMusher** [comment]
@AskBojesen > Disconnecting from app - which app on which platform?

It is my test app running on top of your library on Windows. I've checked the old code and it seems like it does something else than how it is done in the WinConsole. 
So I believe the issue is on my side this time.

**Comment by AskBojesen** [comment]
> > > @janusw You're right that it must be the runtime that messes it up
> > > 
> > > 1. Which Windows version are you targeting in your application?
> > >    I target net8.0-windows10.0.22621.0 as that is what the WinConsole sample is using
> > > 2. Which Windows version are you actually running it on?
> > >    My laptop only runs 10.0.19045 so that must be what causing the problem.
> 
> Thanks for the info. This indeed confirms my suspicion.
> 
> > you need runtime check if running on Windows 10, or you must use another target than 10.0.22621 Unfortunately Windows has no check for runtime - you simply get exceptions has you saw!
> 
> Well, I think the library should better guard the version-dependent code by a runtime check and only execute it if it's supported (see https://learn.microsoft.com/en-us/windows/uwp/debug-test-perf/version-adaptive-apps).
> 
> For `BluetoothLEDevice.GetConnection` one needs to check for `UniversalApiContract` v14 AFAICS.

I agree - that it is dangerous as it is now - I got a nasty surprise myself trying to run the desktop app on Windows 10.
But @janusw : Can we keep focus on this PR for the original  connection lost issue - and create another PR for Windows Runtime awareness ?

**Comment by AskBojesen** [comment]
@CodeMusher , @axa88 : Can you please confirm, that the original issue for this PR is solved?

Original issue: not connection lost of lost without client request

**Comment by AskBojesen** [comment]
Note: open issues not fixed in this PR:

- https://github.com/dotnet-bluetooth-le/dotnet-bluetooth-le/issues/852
- https://github.com/dotnet-bluetooth-le/dotnet-bluetooth-le/issues/850
- https://github.com/dotnet-bluetooth-le/dotnet-bluetooth-le/issues/788

When thios PR #849 is approved and merged, then I will look into the three issues above

**Comment by axa88** [comment]
> @CodeMusher , @axa88 : Can you please confirm, that the original issue for this PR is solved?
> 
> Original issue: not connection lost of lost without client request

@AskBojesen 
Im unable to confirm anything regarding this issue.  With this build it doesn't take much more than 2 connect/disconnect cycles before my device is left in an unusable state which will no longer connect/disconnect as reported elsewhere.

I can report the first connect/disconnect/lost cycle does appear to work.  But just not anything past that.

**Comment by CodeMusher** [comment]
I believe my initial issue is solved by this.

**Review by janusw — APPROVED** [review]
> I believe my initial issue is solved by this.

Alright, then let's merge it. The modification of the library itself is rather simple, after all, and ok with me.

**Pull request merged**
